version: "3.8"

services:

  zipkin:
    image: openzipkin/zipkin
    mem_limit: 700m
    ports:
      - "9411:9411"
    networks:
     - onesuite
  
  configserver:
    image:  ./service/configserver
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
     - onesuite
    depends_on:
      - zipkin
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
          
  eurekaserver:
    image: ./service/configserver
    mem_limit: 700m
    ports:
      - "8070:8070"
    networks:
     - onesuite
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
      
  usermanagement:
    build:  ./usermanagement
    mem_limit: 700m
    ports:
      - "8880:8880"
    depends_on:
      - configserver
      - eurekaserver
      
  notification:
    build:  ./notification
    mem_limit: 700m
    ports:
      - "8881:8881"
    depends_on:
      - configserver
      - eurekaserver
   
       
  gatewayserver:
    image: ./service/configserver
    mem_limit: 700m
    ports:
      - "8072:8072"
    networks:
      - onesuite
    depends_on:
      - configserver
      - eurekaserver
      - notification
      - usermanagement
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 180s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

networks:
  onesuite: